### ISSUE TITLE
jde-jdk-build-default-registry-linux-default-test fails on master branch

### ISSUE THREAD

**Issue by dakrone** [jdee-emacs/jdee#13]
The relevant output is:

```
     [echo] Testing file: /home/hinmanm/src/elisp/jdee/test/lisp/jde-jdk-manager-test.el
     [exec] Running 6 tests (2015-08-14 16:34:08-0600)
     [exec]    passed  1/6  jde--jdk-find-dirs-test
     [exec]    passed  2/6  jde--jdk-get-version-test
     [exec]    passed  3/6  jde-jdk-build-default-registry-darwin-test
     [exec] Test jde-jdk-build-default-registry-linux-default-test backtrace:
     [exec]   (if (unwind-protect (setq value-86759 (apply fn-86757 args-86758)) (
     [exec]   (let (form-description-86761) (if (unwind-protect (setq value-86759 
     [exec]   (let ((value-86759 (quote ert-form-evaluation-aborted-86760))) (let 
     [exec]   (let ((fn-86757 (function equal)) (args-86758 (list (quote (("1.8" .
     [exec]   (progn (fset (quote jde--jdk-find-dirs) vnew) (fset (quote jdk--jdk-
     [exec]   (unwind-protect (progn (fset (quote jde--jdk-find-dirs) vnew) (fset 
     [exec]   (let* ((vnew (function (lambda (path) (string-match "oracle" path)))
     [exec]   (let ((default-jvm-paths (quote ("/usr/lib/jvm" "/usr/lib64/jvm"))))
     [exec]   (lambda nil (let ((default-jvm-paths (quote ("/usr/lib/jvm" "/usr/li
     [exec]   #[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\317\320%DC
     [exec]   funcall(#[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\31
     [exec]   ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
     [exec]   #[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\316%DC\2
     [exec]   funcall(#[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\
     [exec]   ert-run-test([cl-struct-ert-test jde-jdk-build-default-registry-linu
     [exec]   ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test j
     [exec]   ert-run-tests(t #[385 "\306\307\"\203D
     [exec]   ert-run-tests-batch(nil)
     [exec]   ert-run-tests-batch-and-exit()
     [exec]   command-line-1(("-L" "/home/hinmanm/src/elisp/jdee/build/lisp" "--lo
     [exec]   command-line()
     [exec]   normal-top-level()
     [exec] Test jde-jdk-build-default-registry-linux-default-test condition:
     [exec]     (ert-test-failed
     [exec]      ((should
     [exec]        (equal '...
     [exec] 	(jde-jdk-build-default-registry)))
     [exec]       :form
     [exec]       (equal
     [exec]        (("1.8" . "/usr/lib/jvm/java-8-oracle")
     [exec] 	("1.7" . "/usr/lib/jvm/java-7-oracle")
     [exec] 	("1.6" . "/usr/lib/jvm/java-6-oracle"))
     [exec]        nil)
     [exec]       :value nil :explanation
     [exec]       (different-types
     [exec]        (("1.8" . "/usr/lib/jvm/java-8-oracle")
     [exec] 	("1.7" . "/usr/lib/jvm/java-7-oracle")
     [exec] 	("1.6" . "/usr/lib/jvm/java-6-oracle"))
     [exec]        nil)))
     [exec]    FAILED  4/6  jde-jdk-build-default-registry-linux-default-test
     [exec]    passed  5/6  jde-jdk-build-default-registry-linux-no-jdks-test
     [exec]    passed  6/6  jde-jdk-build-default-registry-test
     [exec] 
     [exec] Ran 6 tests, 5 results as expected, 1 unexpected (2015-08-14 16:34:08-0600)
     [exec] 
     [exec] 1 unexpected results:
     [exec]    FAILED  jde-jdk-build-default-registry-linux-default-test
     [exec] 

```

Full output here: https://gist.github.com/dakrone/b0de6547e6db6e2a2530

**Comment by dakrone** [comment]
If no one gets to this before me, I will take a look.

**Comment by pwojnowski** [comment]
Fixed. It was a typo in mocked function name. Sorry. :-|

**Comment by dakrone** [comment]
@pwojnowski this test is still failing on the latest master even after your fix:

```
     [exec] Test jde-jdk-build-default-registry-linux-default-test condition:
     [exec]     (ert-test-failed
     [exec]      ((should
     [exec]        (equal '...
     [exec] 	(jde-jdk-build-default-registry)))
     [exec]       :form
     [exec]       (equal
     [exec]        (("1.8" . "/usr/lib/jvm/java-8-oracle")
     [exec] 	("1.7" . "/usr/lib/jvm/java-7-oracle")
     [exec] 	("1.6" . "/usr/lib/jvm/java-6-oracle"))
     [exec]        (("1.8" . "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-4.b16.fc22.x86_64")
     [exec] 	("1.8" . "/usr/lib/jvm/java-8-oracle")
     [exec] 	("1.7" . "/usr/lib/jvm/java-7-oracle")
     [exec] 	("1.6" . "/usr/lib/jvm/java-6-oracle")))
     [exec]       :value nil :explanation
     [exec]       (proper-lists-of-different-length 3 4
     [exec] 					(("1.8" . "/usr/lib/jvm/java-8-oracle")
     [exec] 					 ("1.7" . "/usr/lib/jvm/java-7-oracle")
     [exec] 					 ("1.6" . "/usr/lib/jvm/java-6-oracle"))
     [exec] 					(("1.8" . "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-4.b16.fc22.x86_64")
     [exec] 					 ("1.8" . "/usr/lib/jvm/java-8-oracle")
     [exec] 					 ("1.7" . "/usr/lib/jvm/java-7-oracle")
     [exec] 					 ("1.6" . "/usr/lib/jvm/java-6-oracle"))
     [exec] 					first-mismatch-at 0)))
     [exec]    FAILED  4/6  jde-jdk-build-default-registry-linux-default-test
     [exec]    passed  5/6  jde-jdk-build-default-registry-linux-no-jdks-test
     [exec]    passed  6/6  jde-jdk-build-default-registry-test
     [exec] 
     [exec] Ran 6 tests, 5 results as expected, 1 unexpected (2015-08-14 17:17:14-0600)
     [exec] 
     [exec] 1 unexpected results:
     [exec]    FAILED  jde-jdk-build-default-registry-linux-default-test
     [exec] 
```

**Comment by pwojnowski** [comment]
Hm... strange. All tests pass on my machine. I guess that you will have to find out why it fails, because I cannot reproduce it now. Could you check whether
((symbol-function 'jde--jdk-p)
    (lambda (path)
       (string-match "oracle" path)))
is called?
